---

- name: Install repos required to get PHP 8
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: PHP Installs
  yum:
    enablerepo: "remi-php82"
    name:
      - php-cli
      - php-mysqlnd
      - php-mbstring
      - php-json
      - php-xml
      - php-pecl-zip
      - php-fpm

- name: Ensure PHP FPM is running
  systemd:
    name: php-fpm
    enabled: yes
    state: started
