all:
  children:
    shopify_connector:
      hosts:
        # Replace "replace_me" with the domain name of the server being setup
        # or else ssl/httpd will not be configured correctly
        # (e.g. connector.my-server.com)
        replace_me:
          # Replace these with the server info you're setting up
          ansible_ssh_private_key_file: ''
          ansible_host: ''
          ansible_user: ''
          ansible_port: 22

      vars:
        base_path: '..'

        git:
          repo_dest: "/var/www/shopify-connector"

        httpd:
          document_root: "{{git.repo_dest}}/public_html"
          ssl: true
          ssl_email: ''

        mysqld:
          mycnf: "{{base_path}}/files/mysql/data/my.cnf"
